---
title: Contributing
format: html
---


Hey, it's great that you want to contribute to the project!

Landelijke Docs is open-source, and as such, anyone can contribute! For those used to using git repositories the process will be familiar.

You are welcome to contribute to our platform in two ways.

- Create a new Codeberg Issue

|       Head over to our issue page on Codeberg to let us know about bugs, feature requests for the website, or anything that you would love to see developed for your 
|       research project (e.g., a code snippet). You can also attach files.

- Contribute directly via Pull Requests

Already familiar with Codeberg and Pull Requests? Than fork our repository, work on your changes in a fresh branch, and submit a pull request.

Need a step-by-step tutorial on how to do that? [Read more about pull requests here](https://docs.codeberg.org/collaborating/pull-requests-and-git-flow/).

# What is a contribution?

Anything from simple changes, grammar checks and reporting a bug to more elaborate changes and writing entirely new content!

We basically welcome any kind of feedback and contribution, including but not limited to:

-   general fixes (typos, small sentences)
-   elaborate changes (modifying, adding or removing an entire paragraph or chapter)
-   asking for new content to be added
-   submitting an article without worrying about formatting (even a Word file!)
-   reporting a bug
-   requesting a new feature on the website
-   general tips or questions on the project
-   beautification work
-   graphics to use in or out of articles

# How is the content organized?

We currently provide content in five categories:

*   Articles are concepts in small doses, the DNA of our platform. They are short guides on a subtopic teaching fundamental concepts in software development. Information is explained in a way that it is easy to clone or implement in an existing project. While everybody can follow our articles, they are generally more appealing to advanced users – or those who already know what to look for.

*   Paths are collections of articles relevant to a role or type of project that will be interspersed with examples for learners to follow. 

*   Programmes are institution crafted paths. Some institutions might prefer their own materials or think that more or fewer article should be in a path.

*   The Learning Bank contains all learning resources created by our partners and contributors.

*   Outside resources, a list of organised links for 3rd party resources that contributors have found to be useful and well written/spoken/filmed.

# Contribution Guides

In order to help with your contributions we some guidelines and templates. You can find the templates [here in the repo](https://codeberg.org/Landelijke-Docs/pages/src/branch/main/templates), the style guide can be [found here]() and [the readme](https://codeberg.org/Landelijke-Docs/pages/src/branch/main/README.md) has some information about the basics of Quarto (what this project uses to create the website). If you think that we could do with some more guides or templates then please raise it as an [issue in the repo](https://codeberg.org/Landelijke-Docs/pages/issues)! :)


# TODO list


-_-_-_- Dev work -_-_-_-

- [Add pdf viewing for learning bank](https://codeberg.org/Landelijke-Docs/pages/issues/1)
- [Create upload page to avoid needing a codeberg account and knowledge on forking](https://codeberg.org/Landelijke-Docs/pages/issues/2)
- [connect to turing way](https://codeberg.org/Landelijke-Docs/pages/issues/3)
- [connect to taxila](https://codeberg.org/Landelijke-Docs/pages/issues/4)
- [connect to escience center](https://codeberg.org/Landelijke-Docs/pages/issues/5)
- [add embedded notebooks](https://codeberg.org/Landelijke-Docs/pages/issues/6)
- [Create options for including (R) Shiny in pages](https://codeberg.org/Landelijke-Docs/pages/issues/7)
- [add embedded r coding](https://codeberg.org/Landelijke-Docs/pages/issues/8)
- [integrate reading level check tools as part of actions (hemmingway/gunning fog index)](https://codeberg.org/Landelijke-Docs/pages/issues/9)
- [Create a tool to convert powerpoint to pdf or html ready for integration](https://codeberg.org/Landelijke-Docs/pages/issues/10)

******* Design work *******

- Create set of graphics to use in articles [1](https://codeberg.org/Landelijke-Docs/pages/issues/11), [2](https://codeberg.org/Landelijke-Docs/pages/issues/12)
- [Create graphics to break up reading lots of articles](https://codeberg.org/Landelijke-Docs/pages/issues/13)
- [Beautify site](https://codeberg.org/Landelijke-Docs/pages/issues/14)
- [Review the UI of the site](https://codeberg.org/Landelijke-Docs/pages/issues/15)
- [Write up YAML to allow Codeberg actions to automate commit to website process and hosting in Codeberg pages](https://codeberg.org/Landelijke-Docs/pages/issues/33)
- [Create tool to allow contributors to make quizzes](https://codeberg.org/Landelijke-Docs/pages/issues/36)

<><><>< Writing ><><><>

- articles from basics topics
- niche topics with best practice
- homeworks
- Quizzes
- [update sales pitch to presentation others can re-use](https://codeberg.org/Landelijke-Docs/pages/issues/37)
- [Add a guide on how to contribute to a course](https://codeberg.org/Landelijke-Docs/pages/issues/34)
- [Refine CoC and credit as desired by license](https://codeberg.org/Landelijke-Docs/pages/issues/28)
- [Refine the contributing doc and credit as desired by license](https://codeberg.org/Landelijke-Docs/pages/issues/39)
- [Refine the  accessbility doc and credit as desired by license](https://codeberg.org/Landelijke-Docs/pages/issues/40)

<^><^><^> Structure <^><^><^>

- [Create paths page](https://codeberg.org/Landelijke-Docs/pages/issues/16)
- [Create programmes (institute specific paths) page](https://codeberg.org/Landelijke-Docs/pages/issues/17)
- [Finish the learning bank page](https://codeberg.org/Landelijke-Docs/pages/issues/18)
- [Make 3rd party resource page, add categories/filters (maybe use quarto listing?)](https://codeberg.org/Landelijke-Docs/pages/issues/19)
- [Form topic list](https://codeberg.org/Landelijke-Docs/pages/issues/20)
- [Form subtopic list](https://codeberg.org/Landelijke-Docs/pages/issues/21)
- [make a guide template](https://codeberg.org/Landelijke-Docs/pages/issues/23)
- [make a programme template](https://codeberg.org/Landelijke-Docs/pages/issues/24)
- [update article/subtopic template](https://codeberg.org/Landelijke-Docs/pages/issues/25)
- [Fix up the documentation style guide as an example](https://codeberg.org/Landelijke-Docs/pages/issues/26)
- [set up email address](https://codeberg.org/Landelijke-Docs/pages/issues/27)
- [Add in development section to learning bank](https://codeberg.org/Landelijke-Docs/pages/issues/29)
- [Make metadata template for courses & materials](https://codeberg.org/Landelijke-Docs/pages/issues/30)
- [Get CC license and link to it in footer](https://codeberg.org/Landelijke-Docs/pages/issues/31#issuecomment-10006755)
- [fix codeberg icon to exist in the navbar](https://codeberg.org/Landelijke-Docs/pages/issues/32)
- [Apply documentation guidelines to regular pages, e.g. landing pages, about, etc](https://codeberg.org/Landelijke-Docs/pages/issues/38)
- [Create a homework section to allow uploads and contributions](https://codeberg.org/Landelijke-Docs/pages/issues/35)
