on:
  push:
    branches:
      - pages

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: codeberg-small
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Publish
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: 'https://${{ forge.repository_owner }}.codeberg.page/'
          token: ${{ forge.token }}
          source: _site/